# Generated by Django 4.1.3 on 2023-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('cedula', models.IntegerField()),
                ('correo', models.CharField(max_length=40)),
                ('carrera', models.CharField(max_length=80)),
                ('paralelo', models.CharField(max_length=10)),
                ('jornada', models.CharField(max_length=20)),
                ('telefono', models.FloatField()),
                
            ],
        ),
    ]
